services:
  graphiql:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: graphiql-explorer:${DOCKER_ENV}
    ports:
      - "4000:4000"
    env_file:
      - ./inbuilt/.env
    restart: on-failure
